title: CLArgs Documentation
description: The documentation for the CLArgs command-line argument parsing library.
theme: just-the-docs

url: https://rsore.github.io/clargs/

aux_links:
  Github Repository: https://github.com/rsore/clargs
