name: clang-tidy-review
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review
      with:
        cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
