name: clang-tidy-review
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run clang-tidy
      uses: ZedThree/clang-tidy-review@v0.19.0
      id: review
      with:
        build_dir: build
        config_file: ".clang-tidy"
        cmake_command: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE" && \
          cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
                           -DCLARGS_BUILD_EXAMPLES=ON \
                           -DCLARGS_BUILD_TESTS=ON

    - uses: ZedThree/clang-tidy-review/upload@v0.14.0
      id: upload-review